# Lookup Tables

Lookup tables are a special kind of tables in DataJoint that are used to store static data or enumerations that don't change frequently.

The contents of lookup tables is considered part of schema design: they are populated at the time of table declaration.
When a new instance of the database is initiated, lookup tables get populated immediately and the database is still considered "empty."

Although technically the contents of lookup tables can change overtime, this should be considered a rare even, part of schema design alteration and not a normal database operation. 


Lookup tables are particularly useful for maintaining data consistency and enforcing referential integrity in your database. 

Lookup tables are created by subclassing the `dj.Lookup` class. 
Rather than using `insert` commands to populate lookup tables, its contents should be provided in the `contents` member of the table class.
The `@schema` decorator declares the table and populates its from the `contents` class member.


## Examples
The following are some examples of lookup tables.

In [2]:
import datajoint as dj
schema = dj.Schema('learning_lookups')

[2025-10-31 21:02:01,675][INFO]: DataJoint 0.14.6 connected to dev@db:3306

### Example: Letter grades
Consider the lookup table that converts letter grades into their numerical point values. The primary key is the letter grade. The points are of type `decimal(3,2)`.

In [3]:
@schema
class LetterGrade(dj.Lookup):
    definition = """
    grade_letter: char(2)  # Letter grade
    ----
    grade_point = null: decimal(3,2) unsigned     # Corresponding grade point
    """
    contents = [
        ('A', 4.00), ('A-', 3.67), ('B+', 3.33), ('B', 3.00), ('B-', 2.67), ('C+', 2.33),
        ('C', 2.00), ('C-', 1.67), ('D+', 1.33), ('D', 1.00), ('F', 0.00), ('I', None)
    ]

In [4]:
LetterGrade()

*grade_letter  grade_point
+------------+ +------------+
A              4.00
A-             3.67
B              3.00
B-             2.67
B+             3.33
C              2.00
C-             1.67
C+             2.33
D              1.00
D+             1.33
F              0.00
I              None
 (Total: 12)

Note that the point value is nullable, it can be set to `NULL`, which is represented by `None` in Python.

### Example: Gene Information in Genomics Research
In genetics or genomics research, a lookup table can hold gene information to ensure consistency across datasets.

In [5]:
@schema
class Gene(dj.Lookup):
    definition = """
    gene_name: varchar(32)  # Gene symbol or name
    ----
    full_name: varchar(255)  # Full name or description of the gene
    """
    contents = [
        ('BRCA1', 'Breast cancer type 1 susceptibility protein'),
        ('TP53', 'Tumor protein p53')
    ]

## Example: Periodic Table of Elements

For a more substantial example, consider the lookup table for the chemical elements.

In [6]:
elements = [
    (1, 'Hydrogen', 'H', 1.008, '1s1'), (2, 'Helium', 'He', 4.0026, '1s2'),
    (3, 'Lithium', 'Li', 6.94, '[He] 2s1'), (4, 'Beryllium', 'Be', 9.0122, '[He] 2s2'), 
    (5, 'Boron', 'B', 10.81, '[He] 2s2 2p1'), (6, 'Carbon', 'C', 12.011, '[He] 2s2 2p2'), 
    (7, 'Nitrogen', 'N', 14.007, '[He] 2s2 2p3'), (8, 'Oxygen', 'O', 15.999, '[He] 2s2 2p4'), 
    (9, 'Fluorine', 'F', 18.998, '[He] 2s2 2p5'), (10, 'Neon', 'Ne', 20.18, '[He] 2s2 2p6'), 
    (11, 'Sodium', 'Na', 22.99, '[Ne] 3s1'), (12, 'Magnesium', 'Mg', 24.305, '[Ne] 3s2'),
    (13, 'Aluminum', 'Al', 26.982, '[Ne] 3s2 3p1'), (14, 'Silicon', 'Si', 28.085, '[Ne] 3s2 3p2'), 
    (15, 'Phosphorus', 'P', 30.974, '[Ne] 3s2 3p3'), (16, 'Sulfur', 'S', 32.06, '[Ne] 3s2 3p4'),
    (17, 'Chlorine', 'Cl', 35.45, '[Ne] 3s2 3p5'), (18, 'Argon', 'Ar', 39.948, '[Ne] 3s2 3p6'),
    (19, 'Potassium', 'K', 39.098, '[Ar] 4s1'), (20, 'Calcium', 'Ca', 40.078, '[Ar] 4s2'),
    (21, 'Scandium', 'Sc', 44.956, '[Ar] 3d1 4s2'), (22, 'Titanium', 'Ti', 47.867, '[Ar] 3d2 4s2'),
    (23, 'Vanadium', 'V', 50.942, '[Ar] 3d3 4s2'), (24, 'Chromium', 'Cr', 51.996, '[Ar] 3d5 4s1'),
    (25, 'Manganese', 'Mn', 54.938, '[Ar] 3d5 4s2'), (26, 'Iron', 'Fe', 55.845, '[Ar] 3d6 4s2'), 
    (27, 'Cobalt', 'Co', 58.933, '[Ar] 3d7 4s2'), (28, 'Nickel', 'Ni', 58.693, '[Ar] 3d8 4s2'),
    (29, 'Copper', 'Cu', 63.546, '[Ar] 3d10 4s1'), (30, 'Zinc', 'Zn', 65.38, '[Ar] 3d10 4s2'),
    (31, 'Gallium', 'Ga', 69.723, '[Ar] 3d10 4s2 4p1'), (32, 'Germanium', 'Ge', 72.63, '[Ar] 3d10 4s2 4p2'), 
    (33, 'Arsenic', 'As', 74.922, '[Ar] 3d10 4s2 4p3'), (34, 'Selenium', 'Se', 78.971, '[Ar] 3d10 4s2 4p4'), 
    (35, 'Bromine', 'Br', 79.904, '[Ar] 3d10 4s2 4p5'), (36, 'Krypton', 'Kr', 83.798, '[Ar] 3d10 4s2 4p6'), 
    (37, 'Rubidium', 'Rb', 85.468, '[Kr] 5s1'), (38, 'Strontium', 'Sr', 87.62, '[Kr] 5s2'), 
    (39, 'Yttrium', 'Y', 88.906, '[Kr] 4d1 5s2'), (40, 'Zirconium', 'Zr', 91.224, '[Kr] 4d2 5s2'), 
    (41, 'Niobium', 'Nb', 92.906, '[Kr] 4d3 5s2'), (42, 'Molybdenum', 'Mo', 95.95, '[Kr] 4d4 5s2'), 
    (43, 'Technetium', 'Tc', 98, '[Kr] 4d5 5s2'), (44, 'Ruthenium', 'Ru', 101.07, '[Kr] 4d6 5s2'), 
    (45, 'Rhodium', 'Rh', 102.91, '[Kr] 4d7 5s2'), (46, 'Palladium', 'Pd', 106.42, '[Kr] 4d8 5s2'), 
    (47, 'Silver', 'Ag', 107.87, '[Kr] 4d10'), (48, 'Cadmium', 'Cd', 112.41, '[Kr] 4d10 5s2'), 
    (49, 'Indium', 'In', 114.82, '[Kr] 4d10 5s2 5p1'), (50, 'Tin', 'Sn', 118.71, '[Kr] 4d10 5s2 5p2'), 
    (51, 'Antimony', 'Sb', 121.76, '[Kr] 4d10 5s2 5p3'), (52, 'Tellurium', 'Te', 127.6, '[Kr] 4d10 5s2 5p4'), 
    (53, 'Iodine', 'I', 126.9, '[Kr] 4d10 5s2 5p5'), (54, 'Xenon', 'Xe', 131.29, '[Kr] 4d10 5s2 5p6'), 
    (55, 'Cesium', 'Cs', 132.91, '[Xe] 6s1'), (56, 'Barium', 'Ba', 137.33, '[Xe] 6s2'), 
    (57, 'Lanthanum', 'La', 138.91, '[Xe] 4f1 5d1 6s2'), (58, 'Cerium', 'Ce', 140.12, '[Xe] 4f2 6s2'), 
    (59, 'Praseodymium', 'Pr', 140.91, '[Xe] 4f3 6s2'), (60, 'Neodymium', 'Nd', 144.24, '[Xe] 4f4 6s2')]

@schema
class Element(dj.Lookup):
    definition = """
    atomic_number : tinyint unsigned 
    ---
    element : varchar(30)
    symbol  : char(2)
    atomic_weight  : float 
    electron_orbitals : varchar(20)
    unique index(symbol)
    """
    contents = elements

In [44]:
Element()

*atomic_number element       symbol     atomic_weight  electron_orbit
+------------+ +-----------+ +--------+ +------------+ +------------+
1              Hydrogen      H          1.008          1s1
2              Helium        He         4.0026         1s2
3              Lithium       Li         6.94           [He] 2s1
4              Beryllium     Be         9.0122         [He] 2s2
5              Boron         B          10.81          [He] 2s2 2p1
6              Carbon        C          12.011         [He] 2s2 2p2
7              Nitrogen      N          14.007         [He] 2s2 2p3
8              Oxygen        O          15.999         [He] 2s2 2p4
9              Fluorine      F          18.998         [He] 2s2 2p5
10             Neon          Ne         20.18          [He] 2s2 2p6
11             Sodium        Na         22.99          [Ne] 3s1
12             Magnesium     Mg         24.305         [Ne] 3s2
   ...
 (Total: 60)

## Why Use Lookup Tables?
* **Consistency**: Lookup tables enforce consistent use of values across your database, reducing the risk of data entry errors.
* **Referential Integrity**: By linking other tables to a lookup table, you ensure that only valid, predefined values are used.
* **Ease of Updates**: If a standard value needs to change (e.g., correcting a typo in a species name), it only needs to be updated in one place.

In summary, lookup tables are powerful tools in DataJoint for maintaining the consistency and integrity of your data, especially when dealing with standardized or repeated information across multiple tables in your schema.